AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless backend with API Gateway (REST), Lambda (Python), and DynamoDB.

Globals:
  Function:
    Runtime: python3.12
    Timeout: 15
    MemorySize: 256
    Tracing: Active
    Environment:
      Variables:
        TABLE_NAME: !Ref PropertiesTable
        ENVIRONMENT: !Ref EnvironmentName
    Layers:
      - !Ref CommonLayer

Parameters:
  EnvironmentName:
    Type: String
    Default: dev
  ApiKeyValue:
    Type: String
    NoEcho: true
    Description: API key value for API Gateway Usage Plan. Provide a secure random string.

  JwtSecret:
    Type: String
    NoEcho: true
    Default: dev-change-me
    Description: Secret used to sign JWTs for login.

  Provider:
    Type: String
    Default: RAIDAPI
    AllowedValues:
      - RAIDAPI
      - APIFY
    Description: External provider for listings.

  ProviderApiKey:
    Type: String
    NoEcho: true
    Default: ""
    Description: API key/token for the chosen provider.

  ListingsUrl:
    Type: String
    Default: ""
    Description: Full URL for provider listings endpoint.

  ListingUrl:
    Type: String
    Default: ""
    Description: URL template for single listing endpoint, may include {id}.

  LayerVersionStamp:
    Type: String
    Default: ""
    Description: Stamp to force a new LayerVersion (e.g., commit SHA)

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub properties-api-${EnvironmentName}
      StageName: v1
      TracingEnabled: true
      EndpointConfiguration: REGIONAL
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Api-Key'"
        AllowOrigin: "'*'"
      Auth:
        ApiKeyRequired: true

  # DynamoDB table to store properties
  PropertiesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub properties-${EnvironmentName}
      PrimaryKey:
        Name: id
        Type: String
      SSESpecification:
        SSEEnabled: true
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  # DynamoDB table for users
  UsersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub users-${EnvironmentName}
      PrimaryKey:
        Name: email
        Type: String
      SSESpecification:
        SSEEnabled: true
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  # Lambda Layer for shared code and third-party deps
  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub common-layer-${EnvironmentName}
      Description: !Sub "Common utilities and dependencies (${EnvironmentName}) ${LayerVersionStamp}"
      ContentUri: src/layers/common
      CompatibleRuntimes:
        - python3.12
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.12
      # Let SAM's default Python layer builder copy sources and install deps
      # from requirements.txt into the layer's python/ directory.

  # Functions
  ListPropertiesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub list-properties-${EnvironmentName}
      CodeUri: src/functions/list_properties
      Handler: app.handler
      Policies: []
      Environment:
        Variables:
          PROVIDER: !Ref Provider
          PROVIDER_API_KEY: !Ref ProviderApiKey
          LISTINGS_URL: !Ref ListingsUrl
          LISTING_URL: !Ref ListingUrl
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /properties
            Method: GET
            Auth:
              ApiKeyRequired: true

  GetPropertyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub get-property-${EnvironmentName}
      CodeUri: src/functions/get_property
      Handler: app.handler
      Policies: []
      Environment:
        Variables:
          PROVIDER: !Ref Provider
          PROVIDER_API_KEY: !Ref ProviderApiKey
          LISTINGS_URL: !Ref ListingsUrl
          LISTING_URL: !Ref ListingUrl
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /properties/{id}
            Method: GET
            Auth:
              ApiKeyRequired: true

  SyncRealtorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub sync-realtor-${EnvironmentName}
      CodeUri: src/functions/sync_realtor
      Handler: app.handler
      Timeout: 30
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PropertiesTable
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /internal/sync/realtor
            Method: POST
            Auth:
              ApiKeyRequired: true

  SyncZillowFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub sync-zillow-${EnvironmentName}
      CodeUri: src/functions/sync_zillow
      Handler: app.handler
      Timeout: 30
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PropertiesTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /internal/sync/zillow
            Method: POST
            Auth:
              ApiKeyRequired: true

  # API Key and Usage Plan
  RestApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: !Sub properties-api-key-${EnvironmentName}
      Enabled: true
      Value: !Ref ApiKeyValue
      # StageKeys removed; association is handled via UsagePlanKey

  RestUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn:
      - Apiv1Stage
    Properties:
      UsagePlanName: !Sub properties-usage-plan-${EnvironmentName}
      ApiStages:
        - ApiId: !Ref Api
          Stage: v1
      Throttle:
        BurstLimit: 10
        RateLimit: 100
      Quota:
        Limit: 100000
        Period: MONTH

  RestUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref RestApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref RestUsagePlan

  # Auth: signup
  SignupFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub signup-${EnvironmentName}
      CodeUri: src/functions/auth_signup
      Handler: app.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Environment:
        Variables:
          USERS_TABLE_NAME: !Ref UsersTable
          JWT_SECRET: !Ref JwtSecret
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /auth/signup
            Method: POST
            Auth:
              ApiKeyRequired: false

  # Auth: login
  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub login-${EnvironmentName}
      CodeUri: src/functions/auth_login
      Handler: app.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UsersTable
      Environment:
        Variables:
          USERS_TABLE_NAME: !Ref UsersTable
          JWT_SECRET: !Ref JwtSecret
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /auth/login
            Method: POST
            Auth:
              ApiKeyRequired: false

Outputs:
  ApiUrl:
    Description: API base URL
    Value: !Sub https://${Api}.execute-api.${AWS::Region}.amazonaws.com/v1
  ApiKeyName:
    Description: API key name to use in X-Api-Key header
    Value: !Ref RestApiKey
  TableName:
    Description: DynamoDB table name
    Value: !Ref PropertiesTable
