name: CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Build
        run: sam build --use-container

      - name: Deploy
        run: |
          sam deploy \
            --no-fail-on-empty-changeset \
            --stack-name ${{ secrets.STACK_NAME }} \
            --s3-prefix ${{ secrets.STACK_NAME }} \
            --resolve-s3 \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides EnvironmentName=${{ secrets.ENVIRONMENT_NAME }} ApiKeyValue=${{ secrets.API_KEY_VALUE }}

